### ISSUE TITLE
Housekeeping, but...

### ISSUE THREAD

**Issue by DonnKey** [jaredsburrows/gradle-license-plugin#108]
I'm seeing the following warning, which wouldn't concern me except for the end-of-year deadline:

WARNING: API 'variant.getMergeResources()' is obsolete and has been replaced with 'variant.getMergeResourcesProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getMergeResources(), use -Pandroid.debug.obsoleteApi=true on the command line to display more information.

Donn

**Comment by jaredsburrows** [comment]
I believe you are seeing this from another plugin. I am not using `variant.getMergeResources()` in this plugin.
