### ISSUE TITLE
Cannot add Extension with Name 'licenseReport'

### ISSUE THREAD

**Issue by CleanHit** [jaredsburrows/gradle-license-plugin#120]
I'm trying to find the suitable tool for licensing for me and when I have this one:
```
dependencies {
    classpath 'com.github.jk1:gradle-license-report:1.11'
}

apply plugin: 'com.github.jk1.dependency-license-report' 
```
In my `gradle.build` file I get this error:

```
FAILURE: Build failed with an exception.

* Where:
Build file '<path_to_my_project>\app\build.gradle' line: 144

* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.jaredsburrows.license']
   > Cannot add extension with name 'licenseReport', as there is an extension already registered with that name.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 3s
```

**Comment by hendrep** [comment]
I am getting the same error

**Comment by jaredsburrows** [comment]
What is `com.github.jk1:gradle-license-report`?

**Comment by hendrep** [comment]
It is a different license report generator plugin, I assume the op was testing different plugins and forgot to remove that dependency which has a conflicting extension name. I made the same mistake 🙈

**Comment by CleanHit** [comment]
Ok, I've found some information in previous bug reports and I'm not getting the error anymore. What I did is:

1. Put the information below into the `build.gradle` file where the `buildscript` section is defined.
```gradle
plugins {
    id 'com.github.jk1.dependency-license-report' version '1.12' // Newer versions may exist.
}
```
2. For convenience reasons I've created a different `dependency_license_scan.gradle` file for applying the plugin and for managing some of its settings with:

```gradle
apply plugin: 'com.github.jk1.dependency-license-report'    

licenseReport {
// Set output directory for the report data.
// Defaults to ${project.buildDir}/reports/dependency-license.
outputDir = "$projectDir/oss_scan_results"

// Select projects to examine for dependencies.
// Defaults to current project and all its subprojects 
projects = [project] + project.subprojects

// Set the configurations to fetch dependencies. It's very important if your app uses flavors,
// otherwise the scan won't produce results. Default is 'runtimeClasspath'.
configurations = ['put_you_correct_flavor_here']
// Use 'ALL' to dynamically resolve all configurations: 
//configurations = ALL (I didn't use it at the end and can't remeber if it worked)
}
```
3. Import the crated `dependency_license_scan.gradle` file by adding it to your `build.gradle` file where the app dependencies are being imported or hard coded.
```gradle
apply from: <path_to_your_gradle_file>/dependency_license_scan.gradle.gradle>
```

**Comment by CleanHit** [comment]
> 
> 
> It is a different license report generator plugin, I assume the op was testing different plugins and forgot to remove that dependency which has a conflicting extension name. I made the same mistake 🙈

I was still getting the error after commenting out the conflicting extension name.
