### ISSUE TITLE
Is it possible for this to work in a multi-project environment with android and non-android projects

### ISSUE THREAD

**Issue by stealthrabbi** [jaredsburrows/gradle-license-plugin#121]
I am not sure how I'd configure this plugin to work this way. I can't generate a report at hte top level that doesn't simply indicate "none". I also have tried running the task on a particular subproject that has the Android app, but it too does not generate a populated report.

**Comment by jaredsburrows** [comment]
So it always has to be at the per project level?

**Comment by stealthrabbi** [comment]
Are you asking me? I don't understand.

**Comment by jaredsburrows** [comment]
How are you generating reports? By applying the plugin to each android library or app project?

**Comment by jaredsburrows** [comment]
Have you tried this plugin yet?

Similar to https://github.com/jaredsburrows/android-gif-example:

```
// top level build.gradle.kts
plugins {
  id("com.jaredsburrows.license") version "0.8.90" apply false
}
```

```
// app/build.gradles.kts
plugins {
  id("com.jaredsburrows.license")
}
```
