### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by PaulWoitaschek** [jaredsburrows/gradle-license-plugin#123]
It would be great if you could use tags when cutting a release so it's simpler to brows the release history & diff.

**Comment by jaredsburrows** [comment]
Similar to [OkHTTP](https://github.com/square/okhttp/blob/master/CHANGELOG.md) and [RetroFit](https://github.com/square/retrofit/blob/master/CHANGELOG.md), I use a [CHANGELOG.md](https://github.com/jaredsburrows/gradle-license-plugin/blob/master/CHANGELOG.md).

**Comment by PaulWoitaschek** [comment]
That's a different story. OkHttp and Retrofit also use tags. Like the rest of the professional world ✌️

**Comment by PaulWoitaschek** [comment]
The thing is not the github release page. The thing is having git tags. That way you always know what the code was at which version. 
When you now want to navigate back to release x because you want to know when you introduced which bug it's a pain without proper tagging.

**Comment by jaredsburrows** [comment]
Ok cool. I will look into adding tags for newer versions.

**Comment by PaulWoitaschek** [comment]
It's basically just a `git tag 1.2.3` and a `git push --tags`

**Comment by jaredsburrows** [comment]
Done.

**Comment by PaulWoitaschek** [comment]
Yay 🎉
