### ISSUE TITLE
Android: Gradle 6.1 & Android Plugin 4.0 `InstantAppPlugin` failure

### ISSUE THREAD

**Issue by sigmabeta** [jaredsburrows/gradle-license-plugin#126]
When attempting to do a Gradle sync using Android Studio 4.0, the following error occurs:

> Unable to load class 'com.android.build.gradle.InstantAppPlugin'.

Removing this plugin avoids the error. Perhaps some change in the tooling has resulted in this error?

**Comment by jaredsburrows** [comment]
@sigmabeta This should fix https://github.com/jaredsburrows/gradle-license-plugin/pull/127. AFter it is merged, you can try to use the snapshot to test it.

**Comment by kenyee** [comment]
Any ETA on a new release of this plugin?

**Comment by sigmabeta** [comment]
Snapshot works for me, but do you have any updates on when this will be put into a release?

**Comment by luiscurini** [comment]
I would also be interested in a stable release. I'm using the plugin API and I don't get the snapshot to work.

```
could not resolve plugin artifact 
'com.jaredsburrows.gradle-license-plugin:com.jaredsburrows.gradle-license-plugin:0.8.80-SNAPSHOT'
```

**Comment by jaredsburrows** [comment]
`0.8.80` was released today.
