### ISSUE TITLE
methods to fix unknown licenses

### ISSUE THREAD

**Issue by kneep** [jaredsburrows/gradle-license-plugin#132]
Hello. Prompting the user to be aware of the unknown licenses is really a great feature. But we cannot just ship the notice without doing anything. Currently there seems no easy way to correct the information.

1. For very old libraries without license information in the pom, it would be better to give the user a chance to correct the license and then easily go ahead with the process. I would like to have a local file to override the license information for certain packages so that we can still automate the process.

2. Licenses of many pacakges are unknown just because they are proprietary packages pulled from internal repos. So it would be great to a mechanism to exclude packages from certain servers, or with certain prefixes. For example, a variable that users can set the server names or prefixes to.

Thank you.

**Comment by jaredsburrows** [comment]
Can you give an example?

**Comment by jaredsburrows** [comment]
Going to close this for now. This plugin simply generates a report of licenses based on the user given dependencies.
