### ISSUE TITLE
Configuation in Kotlin DSL?

### ISSUE THREAD

**Issue by leonlatsch** [jaredsburrows/gradle-license-plugin#145]
Hey, I want to only use the json report.
But the configuration is never recognized:

![image](https://user-images.githubusercontent.com/50983026/105963972-e5f4b780-6081-11eb-94f2-57f466ab4a83.png)

I am using Kotlin DSL.
Am I just doing it wrong?

My `app/build.gradle.kts`:
```kotlin
plugins {
    id("com.android.application")
    kotlin("android")
    kotlin("kapt")
}

apply(plugin = "androidx.navigation.safeargs.kotlin")
apply(plugin = "dagger.hilt.android.plugin")
apply(plugin = "com.jaredsburrows.license")

android {
    compileSdkVersion(30)
    buildToolsVersion("29.0.3")

    defaultConfig {
        applicationId = "dev.leonlatsch.photok"
        minSdkVersion(24)
        targetSdkVersion(30)
        versionCode = 9
        versionName = "1.2.0"

        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"

        javaCompileOptions {
            annotationProcessorOptions {
                arguments += "room.incremental" to "true"
            }
        }
    }

    buildTypes {
        getByName("release") {
            isMinifyEnabled = false
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro"
            )
        }
    }

    buildFeatures {
        dataBinding = true
    }

    compileOptions {
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    kotlinOptions {
        jvmTarget = "1.8"
    }
}

dependencies {
..............
}

```
Classpath dependency in `build.gradle.kts`: `classpath("com.jaredsburrows:gradle-license-plugin:0.8.90")`

**Comment by Fabbi** [comment]
You have multiple options:
```kotlin
// Configure every Task of Type `LicenseReportTask`
tasks.withType(LicenseReportTask::class).configureEach {
  generateCsvReport = false
  generateHtmlReport = true
  generateJsonReport = false
}
// Configure the default `LicenseReportTask` Task
tasks.named<LicenseReportTask>("licenseReport").configure {
  generateCsvReport = false
  generateHtmlReport = true
  generateJsonReport = false

}
// Create a new Task
tasks.register<LicenseReportTask>("licenseReportHtml") {
  // put it in the same group as the default one
  group = tasks.named<LicenseReportTask>("licenseReport").get().group
  generateCsvReport = false
  generateHtmlReport = true
  generateJsonReport = false
}
```

**Comment by leonlatsch** [comment]
@Fabbi Where do I put this?

**Comment by Fabbi** [comment]
Anywhere really. Where you tried the first time is fine.

**Comment by leonlatsch** [comment]
@Fabbi Hmmm okay. Didn't work in my android project.

**Comment by leonlatsch** [comment]
@Fabbi Is there any difference for the debug and release variants?

**Comment by Fabbi** [comment]
That I can't help you with, I used it in a Java project.

I guess you'd have to configure the `license${variant}Report` Task then?

**Comment by leonlatsch** [comment]
Okay. Maybe @jaredsburrows could help? :)

**Comment by ninniuz** [comment]
@leonlatsch you cannot access plugin extensions with type-safe accessors with Kotlin DSL if you `apply` a plugin. You should add the plugin in the `plugins` block to have Gradle generate type-safe accessors. But I don't know if this plugin is publishing plugin marker dependency, so it might be a bit tricky (you will have to configure a module substitution in your settings.gradle(.kts) file)

**Comment by jaredsburrows** [comment]
@leonlatsch Have you tried what @Fabbi said?

**Comment by leonlatsch** [comment]
@jaredsburrows the solution suggested by @ninniuz worked for me. Using it with an id Statement.

Sorry for not responding.
