### ISSUE TITLE
Jcenter/Bintray are shutting off on May 1st 2021

### ISSUE THREAD

**Issue by iliaskomp** [jaredsburrows/gradle-license-plugin#146]
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

According to the `README.md` of this project the jcenter repository is needed.

Are there any plans to migrate to an alternative repository?

**Comment by jaredsburrows** [comment]
Thanks! Created this

https://issues.sonatype.org/browse/OSSRH-64436

**Comment by huahouzwift** [comment]
Any update on this? We are moving away from JCenter but this is a blocker.

**Comment by jaredsburrows** [comment]
I will publish a new release soon.

**Comment by hamishmaclean** [comment]
there is a bintray kotlinx sub-dependency that is failing to resolve now

**Comment by smohammad** [comment]
Any updates on this? It cannot be found on `mavenCentral()`, although the README seems to say it is.

```> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find com.jaredsburrows:gradle-license-plugin:0.8.90.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/jaredsburrows/gradle-license-plugin/0.8.90/gradle-license-plugin-0.8.90.pom
       - https://repo.maven.apache.org/maven2/com/jaredsburrows/gradle-license-plugin/0.8.90/gradle-license-plugin-0.8.90.pom```

**Comment by josephyanks** [comment]
We are now experiencing this as well (started this AM). Same error as above, but with:

```
> Could not resolve all artifacts for configuration ':classpath'.
> Could not resolve com.jaredsburrows:gradle-license-plugin:0.8.90.
      Required by:
          project :
       > Could not resolve com.jaredsburrows:gradle-license-plugin:0.8.90.
          > Could not get resource 'https://plugins.gradle.org/m2/com/jaredsburrows/gradle-license-plugin/0.8.90/gradle-license-plugin-0.8.90.module'.
             > Could not GET 'https://jcenter.bintray.com/com/jaredsburrows/gradle-license-plugin/0.8.90/gradle-license-plugin-0.8.90.module'. Received status code 502 from server: Bad Gateway
```

**Comment by another-dave** [comment]
I managed to resolve the plugin OK (tested with `./gradlew clean assembleDebug --no-build-cache --refresh-dependencies`, working fine) by adding the Gradle.org plugins repo to my buildscript repositories in `app/build.gradle`:

```gradle
buildscript {
    repositories {
        google()
        maven { url 'https://plugins.gradle.org/m2' }
    }

    dependencies {
        classpath 'com.jaredsburrows:gradle-license-plugin:0.8.90'
        // ... more plugins here
    }
}
```
Just mentioning in case it's of use to some of ye.

**Comment by jaredsburrows** [comment]
I have this working here: https://github.com/jaredsburrows/android-gif-example without `jcenter()`.
