### ISSUE TITLE
Doesn't work with gradle 4.0, android plugin 3.0.0

### ISSUE THREAD

**Issue by EricKuck** [jaredsburrows/gradle-license-plugin#16]
`debugCompile` and `releaseCompile` can no longer be resolved directly. Here is the error message:

```
* What went wrong:
Execution failed for task ':app:licenseProductionDevSdkDebugReport'.
> Resolving configuration 'debugCompile' directly is not allowed
```

The stacktrace reveals that this is coming from `LicenseReportTask.groovy:68`.

**Comment by jaredsburrows** [comment]
@EricKuck Thank you, I am going to merge this into https://github.com/jaredsburrows/gradle-license-plugin/issues/14.
