### ISSUE TITLE
fatal error on androidx.annotation

### ISSUE THREAD

**Issue by ciprig** [jaredsburrows/gradle-license-plugin#167]
Execution failed for task ':app:licenseProdReleaseReport'.
> org.xml.sax.SAXParseException; systemId: file:///Users/ciprian.grigor/.gradle/caches/modules-2/files-2.1/androidx.annotation/annotation/1.3.0-alpha01/bead8516d0fc24d4b39d3cdcf05e60433d9ae660/annotation-1.3.0-alpha01.jar; lineNumber: 1; columnNumber: 1; Content is not allowed in prolog.

**Comment by jaredsburrows** [comment]
Do you have an example? I have this working here: https://github.com/jaredsburrows/android-gif-example.

**Comment by keithle888** [comment]
Having the same issue.
