### ISSUE TITLE
Show warnings for missing dependencies

### ISSUE THREAD

**Issue by jaredsburrows** [jaredsburrows/gradle-license-plugin#17]
Based on https://github.com/jaredsburrows/gradle-license-plugin/issues/15#issuecomment-320940346, show warnings for when the plugin "misses" or "skips" a dependency.

**Comment by Tapchicoma** [comment]
Would be nice to have optional setting to fail the build on such `misses` or `skips`. By default should be off.

**Comment by herriojr** [comment]
As long as lack of license info is contained in the json, I'd be happy.

**Comment by jaredsburrows** [comment]
I added basic logging for developers here: https://github.com/jaredsburrows/gradle-license-plugin/commit/08dc12e048c131c67adb06882b8a63dece4dc930#diff-d80ecee9904217d739f465cdc0085e2aR128.

**Comment by jaredsburrows** [comment]
Have you all tried the latest?

**Comment by jaredsburrows** [comment]
Closing for now. If need more logging information, please let me know.
