### ISSUE TITLE
Automatically running report tasks

### ISSUE THREAD

**Issue by MatthewTamlin** [jaredsburrows/gradle-license-plugin#22]
I've been trying to set up my project so that the report generation task for the current build variant automatically runs each time the project is rebuilt, so that I can automatically copy the JSON report into the build variant's  assets directory. I've managed to make the report tasks run on rebuild, but the generated reports are always empty.

Here's the root build.gradle file:
```groovy
buildscript {
	repositories {
		google()
		jcenter()
		mavenCentral()

		maven {
			url 'https://maven.fabric.io/public'
		}

		maven {
			url 'https://oss.sonatype.org/content/repositories/snapshots'
		}
	}

	dependencies {
		classpath 'com.android.tools.build:gradle:3.0.1'
		classpath 'io.fabric.tools:gradle:1.24.5'
		classpath 'com.jakewharton:butterknife-gradle-plugin:9.0.0-SNAPSHOT'
		classpath 'com.jaredsburrows:gradle-license-plugin:0.7.0'
	}
}

allprojects {
	repositories {
		google()
		jcenter()
		mavenCentral()

		maven {
			url 'https://maven.fabric.io/public'
		}

		maven {
			url "https://jitpack.io"
		}
	}
}

apply from: 'dependencies.gradle'

ext.compileSdkVersion = 26
ext.minimumSdkVersion = 17
ext.targetSdkVersion = 26
ext.releaseName = '0.0.0'
ext.releaseCode = 0
ext.buildToolsVersion = '26.0.2'
ext.applicationId = 'TODO'

task clean(type: Delete) {
	delete rootProject.buildDir

	rootProject.getAllprojects().each {
		delete project.buildDir
	}
}
```

Here's the dependencies.gradle file it references (it's just static definitions):
```groovy
ext.dependencies = [
		androidSupport: [
				appCompat: 'com.android.support:appcompat-v7:26.1.0',
				annotations: 'com.android.support:support-annotations:26.1.0',
				cardView: 'com.android.support:cardview-v7:26.1.0',
				design: 'com.android.support:design:26.1.0',
		]

                // Trimmed for relevance
]
```

Here's the build.gradle file for a library subproject:
```groovy
apply plugin: 'com.android.library'
apply plugin: 'com.jaredsburrows.license'

android {
	buildToolsVersion rootProject.ext.buildToolsVersion
	compileSdkVersion rootProject.ext.compileSdkVersion

	defaultConfig {
		minSdkVersion rootProject.ext.minimumSdkVersion
		targetSdkVersion rootProject.ext.targetSdkVersion

		vectorDrawables.useSupportLibrary true
	}

	buildTypes {
		debug {
			// Some buildConfigField declarations
		}

		staging {
			// Some buildConfigField declarations
		}

		release {
			// Some buildConfigField declarations
		}
	}
}

dependencies {
	implementation rootProject.ext.dependencies.androidSupport.appCompat
}

afterEvaluate {
	project.android.libraryVariants.each {
		final buildTypeName = it.name
		final reportTask = tasks.getByName("license${buildTypeName.capitalize()}Report")

		reportTask.doLast {
			// HTML report is not needed
			project.file('src/main/assets/open_source_licenses.html').delete()

			// Remove JSON report from previous build
			project.file("src/${buildTypeName}/assets/licenseReport.json").delete()

			// Copy and rename current report
			copy {
				from 'build/reports/licenses/'
				into "src/${buildTypeName}/assets/"
				include "license${buildTypeName.capitalize()}Report.json"

				rename { fileName ->
					fileName.replace(buildTypeName.capitalize(), '')
				}
			}
		}

		tasks.getByName("assemble${buildTypeName.capitalize()}").dependsOn(reportTask)
	}
}
```

When I use 'Build > Rebuild project' from the Android Studio toolbar, the reporting task for the current build variant runs, and the report is copied to the correct folder, but the report is empty. The JSON report for example just contains `[]`. I've checked the report in the `build/reports/licenses` directory and it's empty too, which means my copy task is fine. 

I think I'm just running the report task at the wrong time. What can be changed so that the the copied report contains the dependencies?

**Comment by jaredsburrows** [comment]
Maybe I should put them in the folder already.

Developers can then use gitignore to ignore the files and let their CI's generate the builds files and update the applications before they publish.

Maybe we can change how this works and/or make it a feature?

**Comment by MatthewTamlin** [comment]
That would be a useful feature. Alternatively developers could specify configuration options via something like:

```groovy
apply plugin: 'com.jaredsburrows.license'

licenseReportOptions {
    makeJsonReport true
    makeHtmlReport false
    // etc
}
```

I've never made a gradle plugin so I don't know if this is feasible or even possible.

There would still be the problem of automatically running the tasks when the project is built. Currently the tasks have to be run manually though the GUI or the command line, which makes running a CI server a bit more difficult.

**Comment by jaredsburrows** [comment]
This is a good idea! Feel free to contribute with a few PRs. I will look into adding this feature soon.

**Comment by MatthewTamlin** [comment]
I've done some research and I think I can make the modifications. I'll try and find some time to make a PR soon.

**Comment by MatthewTamlin** [comment]
As not to break backwards compatibility, I think the default case should be:
- HTML: Created and copied to assets.
- JSON: Created but not copied to assets.

Then for each report type, allow the configuration closure to either:
- Disable the report entirely.
- Only generate the report.
- Generate the report and then copy it to assets.

This has the additional benefit of not breaking the existing tests.

@jaredsburrows what're your thoughts?

**Comment by jaredsburrows** [comment]
@MatthewTamlin Oh sorry, I didn't see you CC'd me on this. I thought you were going to send in a pull request. Sure, I agree!

**Comment by jaredsburrows** [comment]
@MatthewTamlin Any update?

**Comment by MatthewTamlin** [comment]
Haven’t managed to get around to it yet, other projects have been taking up all of my time. I’ll see if I can make some time this weekend.

**Comment by MatthewTamlin** [comment]
I've got everything working locally, I just need to push the branch up so I can open a PR. I'm getting a 403 currently, would you mind giving me push permission?

**Comment by jaredsburrows** [comment]
@MatthewTamlin You have to create a fork, push up to your own repo and then Github will allow you to make a pull request.

**Comment by jaredsburrows** [comment]
Closed by https://github.com/jaredsburrows/gradle-license-plugin/pull/30.
