### ISSUE TITLE
licenseReport unknown property

### ISSUE THREAD

**Issue by paulWyszynski** [jaredsburrows/gradle-license-plugin#221]
Hi,

I'd like to remove some dependencies from the licenseReport task. When I add it to the gradle file, gradle sync fails with the following message:

`Caused by: groovy.lang.MissingPropertyException: Could not set unknown property 'ignoredPatterns' for extension 'licenseReport' of type com.jaredsburrows.license.LicenseReportExtension`

**Comment by jaredsburrows** [comment]
I have not pushed out an update for this yet - https://github.com/jaredsburrows/gradle-license-plugin/pull/218. You can use the snapshot for now.

**Comment by pawlinsky** [comment]
ok thanks. 

Maybe you have an idea about my next issue :)
When I try to run the licenseReport task. I'm getting this error message:
```
* What went wrong:
Execution failed for task ':myApp:licenseReleaseReport'.
> java.lang.StackOverflowError (no error message)
```
This issue happens when I add the Huawei app service as a dependency:
```
//Huawei in app update
    implementation 'com.huawei.hms:appservice:6.1.0.301'
```
affected package names:
com.huawei.hms.*
com.huawei.updatesdk.*

I have excluded these package names with ignoredPatterns, hoped this could fix the issue. I need to update an app to App Gallery.

**Comment by jaredsburrows** [comment]
@pawlinsky I would need to see the full stacktrace. I do not see this plugin mentioned in there.

**Comment by pawlinsky** [comment]
Hi,

ok I've attached the report. I've run it with ./gradlew clean licenseReleaseReport --stacktrace

[licenseReleaseReport.txt](https://github.com/jaredsburrows/gradle-license-plugin/files/9148048/licenseReleaseReport.txt)

**Comment by jaredsburrows** [comment]
Seems like a recursion issue. Can you post your build file?

**Comment by pawlinsky** [comment]
Root build file:
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven {
            url 'https://developer.huawei.com/repo/'
            metadataSources {
                mavenPom()
                artifact()
            }
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:7.2.1'
        classpath 'com.jaredsburrows:gradle-license-plugin:0.9.1-SNAPSHOT'
        classpath 'com.huawei.agconnect:agcp:1.6.0.300'
    }
}

allprojects {
    repositories {
        google()
        maven {
            url 'https://developer.huawei.com/repo/'
        }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
} 
```

App module build file:

```
plugins {
    id 'com.android.application'
    id 'com.jaredsburrows.license'
    id 'com.huawei.agconnect'
}

android {
    compileSdk 32

    defaultConfig {
        applicationId "de.holodecs.huaweiappupdatewithlicenseplugintest"
        minSdk 24
        targetSdk 32
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

licenseReport {
    generateCsvReport = false
    generateHtmlReport = false
    generateJsonReport = true
    copyJsonReportToAssets = true
    ignoredPatterns = ["com.huawei"]
}

dependencies {
    implementation 'com.google.android.material:material:1.6.1'

    implementation 'com.huawei.hms:appservice:6.1.0.301' //this dependency makes ./gradlew licenseDebugReport break
} 
```

**Comment by pawlinsky** [comment]
Hi @jaredsburrows,

can the build files help you? I could upload the whole project as well.

**Comment by jaredsburrows** [comment]
I am not sure, can you try removing some of the dependencies? Such as `huawei`? Although, `ignoredPatterns` should ignore it. Maybe it is stuck somewhere else.

**Comment by jaredsburrows** [comment]
Any update here?

**Comment by jaredsburrows** [comment]
I believe both of these issues are no longer a problem.
