### ISSUE TITLE
Invalid hyperlinks in html report

### ISSUE THREAD

**Issue by harry248** [jaredsburrows/gradle-license-plugin#233]
The generated html report contains hyperlinks like `<a href="#1934118923">Android Navigation UI (2.6.0-alpha03)</a>`. I suppose it shouldn't be like that. The csv, txt and json files contain the correct links.

**Comment by jaredsburrows** [comment]
Can you give an example of the build.gradle with your dependencies?

**Comment by harry248** [comment]
@jaredsburrows Sorry, we've moved to another plugin, I don't have any examples anymore.

**Comment by jaredsburrows** [comment]
`<a href="#1934118923">Android Navigation UI (2.6.0-alpha03)</a>` is for navigating quickly through the HTMl report. HTML report shows the full license.
