### ISSUE TITLE
 Cannot change dependencies of dependency configuration ':app:api' after it has been resolved.

### ISSUE THREAD

**Issue by hosseinabbasi-toast** [jaredsburrows/gradle-license-plugin#234]
I have this in my app build.gradle:
```groovy
...
configurations.all {
    resolutionStrategy.cacheDynamicVersionsFor 5, 'minutes'
    all*.exclude module: 'some-dependency' //hereeeee
    dependencies {
...
```

And when I run `licenseDebugReport`, I get this:
> > Cannot change dependencies of dependency configuration ':app:api' after it has been resolved.

**Comment by t-beckmann** [comment]
Actually it seems the error is just logged and can be ignored safely. However, to get rid of the outputs I changed the execution order so that `licenseReport` runs early:

```
licenseReport {
  ...
}
compileJava.mustRunAfter('licenseReport')
```

Adding the `mustRunAfter` like above is a workaround.

**Comment by jaredsburrows** [comment]
Since this can be ignored safely, closing for now.
