### ISSUE TITLE
Hide versions from report

### ISSUE THREAD

**Issue by kubeliv** [jaredsburrows/gradle-license-plugin#239]
I'm creating this issue as a request for the ability to hide versions from the generated report. I'm considering doing this work myself and opening a pull request, just wanted to see whether work was already planned or any requests on how you'd like the configuration to work.

**Comment by jaredsburrows** [comment]
Currently this is not planned. I am open to PRs. But why hide versions? You can try using the `ignoredPatterns`.

**Comment by jaredsburrows** [comment]
I guess we can simply remove the versions by default.
