### ISSUE TITLE
[Feature] - Show complete license text

### ISSUE THREAD

**Issue by hardysim** [jaredsburrows/gradle-license-plugin#24]
It is possible (and does it make sense) to show the complete license-text instead of just the title and the link?

Just like in the screenshot in the `README.md` here:

<img src="https://www.bignerdranch.com/assets/img/blog/2015/07/screenshot-gmail.png" />

My generated code looks like this:

![image](https://user-images.githubusercontent.com/3737512/33995992-fdd7f6ac-e0df-11e7-968e-668028a9171b.png)

**Comment by jaredsburrows** [comment]
@hardysim Yes, I agree. I want to show all of the license text. It would be nice if we could do this dynamically, I am thinking we can locally store the license files with the plugin.

**Comment by jaredsburrows** [comment]
@hardysim I am looking into working on this now.

**Comment by jaredsburrows** [comment]
@hardysim Please try out the latest `0.8.3` version for this feature.

**Comment by hardysim** [comment]
@jaredsburrows super cool 👍 
Will there be (and when) a new release including this change?

**Comment by jaredsburrows** [comment]
I said it was released is `0.8.3`.
