### ISSUE TITLE
Kotlin projects also use JARs

### ISSUE THREAD

**Issue by juergenzimmermann** [jaredsburrows/gradle-license-plugin#25]
I tried the gradle-license-plugin for a pure Kotlin project. However, I get the following error message:

```
An exception occurred applying plugin request [id: 'com.jaredsburrows.license', version: '0.7.0']
> Failed to apply plugin [id 'com.jaredsburrows.license']
   > License report plugin can only be applied to android or java projects.
```

**Comment by jaredsburrows** [comment]
@juergenzimmermann What version are you using? I have a test for this here: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/test/groovy/com/jaredsburrows/license/LicensePluginJavaSpec.groovy#L19 and the code for it is here: https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicensePlugin.groovy#L11.

**Comment by juergenzimmermann** [comment]
I'm using the following versions:

* gradle-license-plugin 0.7.0
* Gradle 4.4.1
* JDK 9.0.1
* Kotlin 1.2.10

**Comment by jaredsburrows** [comment]
Same. I tested this on the Kotlin module of https://github.com/jaredsburrows/cs-interview-questions/tree/master/kotlin.

What plugin are you using? Those test cover the Kotlin plugins.

**Comment by jaredsburrows** [comment]
I was not able to repro this.

**Comment by juergenzimmermann** [comment]
@jaredsburrows I attached an almost empty project to reproduce the issue.
[tc-25.zip](https://github.com/jaredsburrows/gradle-license-plugin/files/1596124/tc-25.zip)

**Comment by jaredsburrows** [comment]
Can you tell me which Kotlin plugin you are using? This way, I can write a test for it.

Also, it would be nice if you upload this project as an open source project on Github?

**Comment by jaredsburrows** [comment]
@juergenzimmermann This test passes:
```
  @Unroll def "java - #projectPlugin - all tasks created"() {
    given:
    project.apply plugin: projectPlugin
    new LicensePlugin().apply(project)

    when:
    project.evaluate()

    then:
    project.tasks.getByName("licenseReport")

    where:
    projectPlugin << ["kotlin", "kotlin-platform-jvm", "org.jetbrains.kotlin.jvm", "org.jetbrains.kotlin.platform.jvm"]
  }
```

**Comment by jaredsburrows** [comment]
@juergenzimmermann Can you provide a Github repo to reproduce your issue?

**Comment by bjarneheden** [comment]
I have the same error on my project.
But when using the 0.8.1-SNAPSHOT version, it does work.

**Comment by jaredsburrows** [comment]
@bjarneheden Can you give a project hierarchy or a Github link to your project? I want to resolve this issue you all.

**Comment by jaredsburrows** [comment]
@bjarneheden Any update?

**Comment by jaredsburrows** [comment]
@bjarneheden  ?

**Comment by jaredsburrows** [comment]
Closing because no response.

**Comment by jaredsburrows** [comment]
I believe this is fixed in the latest master. Please try the snapshot `0.8.4-SNAPSHOT`.

**Comment by juergenzimmermann** [comment]
The snapshot works fine. I attach my build.gradle and gradle.properties (without your snapshot). Feel free to use it.
[gradle.zip](https://github.com/jaredsburrows/gradle-license-plugin/files/1811257/gradle.zip)

**Comment by jaredsburrows** [comment]
@juergenzimmermann Thanks for getting back to me. I will make another release soon.

**Comment by jaredsburrows** [comment]
@juergenzimmermann I just released `0.8.41`. Thanks for your patience.

**Comment by juergenzimmermann** [comment]
The error is back...

**Comment by jaredsburrows** [comment]
Same error? I am no longer explicitly checking for "Kotlin" as it already
brings in the java plugin.
