### ISSUE TITLE
Question: 0.9.2 changelog missing or wrong tag (0.9.2 instead of 0.9.1)?

### ISSUE THREAD

**Issue by francescocervone** [jaredsburrows/gradle-license-plugin#268]
We have your plugin integrated in our app and we were waiting for the changelog of the `0.9.2` version before updating.
The [changelog](https://github.com/jaredsburrows/gradle-license-plugin/blob/master/CHANGELOG.md) mentions a `0.9.1` version which doesn't exist. 
Also, the changelog was updated in the [`Prepare version 0.9.2`](https://github.com/jaredsburrows/gradle-license-plugin/commit/c239053670b04d78723c92c7d99f6f96afebe1c2) commit.

Is it possible that the changelog refers to the `0.9.2` tag?

**Comment by jaredsburrows** [comment]
@francescocervone Thanks. I should have write `0.9.2`. I just put up a PR.
