### ISSUE TITLE
Plugin unable to find buildFile

### ISSUE THREAD

**Issue by ctmay4** [jaredsburrows/gradle-license-plugin#270]
I have a multi project build setup. I only have a `build.gradle` in the root of the project. I've tried running it both ways:

- `./gradlew licenseReport`   
- `./gradlew app:licenseReport`

Both ways give the same error.

>  - In plugin 'com.jaredsburrows.license' type 'com.jaredsburrows.license.LicenseReportTask' property 'buildFile' specifies file 'C:\prj\seerdms\app\build.gradle' which doesn't exist.
>
>    Reason: An input file was expected to be present but it doesn't exist.

It is looking in the "app" subdirectory no matter how I run it.

**Comment by ctmay4** [comment]
It is a multi-project setup, however everything I've tried doesn't work. I think the way it is set up is kind of non-standard but I can't make changes to it. I gave up and switch over to another plugin which is working well so far. Thanks for your help.

**Comment by jaredsburrows** [comment]
Can you show your project setup/structure here?

**Comment by ctmay4** [comment]
Sorry, it is not open source and I'm not allowed to share it. The basic issue I think is that there is only a single `build.gradle`. The sub-projects do not have build files. The root project manages building everything (25+ sub-projects). I think that is why it is not finding the `build.gradle` since it doesn't exist in any sub-project. I assume this is not a good way to set things up, but again it is a monster and I can't change that right now.
