### ISSUE TITLE
Error when using configuration on version 0.8.0

### ISSUE THREAD

**Issue by bjarneheden** [jaredsburrows/gradle-license-plugin#31]
I get "Error:(123, 0) Could not find method licenseReport() for arguments [build_cqkmblnzf6152h2yrw5tqbk5i$_run_closure2@234d2d61] on project ':app' of type org.gradle.api.Project."
When trying to use configuration using version 0.8.0.

licenseReport {
    generateHtmlReport = false
    generateJsonReport = true
    copyHtmlReportToAssets = false
    copyJsonReportToAssets = true
}

(I only want a JSON report copied to assets, not the html report)

I tried the same thing using the 0.8.1-SNAPSHOT version and then it works just fine.
Any ETA for a release of 0.8.1 so I do not need to use a snapshot version?

**Comment by jaredsburrows** [comment]
@MatthewTamlin @bjarneheden This is my fault but basically we just merged this feature in. Let me take a look into releasing it soon!

**Comment by jaredsburrows** [comment]
@bjarneheden Released `0.8.1` here: https://github.com/jaredsburrows/gradle-license-plugin/commit/6990241e5cfe9bbbe8e4977ddac579ef2f01ee77.
