### ISSUE TITLE
Ignore specify dependency modules? 

### ISSUE THREAD

**Issue by j796160836** [jaredsburrows/gradle-license-plugin#36]
Hi there, 
I would like to thanks Jared Burrows for this awesome project.
I have question about using this project.

1. Does these have the configure settings for ignore specify modules not show up in gradle configuration?
e.g.
```
apply plugin: "com.jaredsburrows.license"

licenseReport {
    ignoreModules = ["...", "...", "..."]
}
```
or something equals or relevant?

2. I found there have `${project.groupId}.${project.artifactId}` show up in accident.
(`${project.groupId}.${project.artifactId}` using Apache License 😂)
<img width="651" alt="screen shot 2018-03-24 at 7 17 07 am" src="https://user-images.githubusercontent.com/686478/37857107-744b8244-2f33-11e8-8201-499e3ace0201.png">

Can I detach it from gradle config? or I need to edit HTMLs manually?

Thanks.

**Comment by jaredsburrows** [comment]
Where is `${project.groupId}.${project.artifactId}` coming from?

**Comment by j796160836** [comment]
@jaredsburrows I don't know actually.

**Comment by qkjerome** [comment]
@jaredsburrows we would also be interested in excluding some artifacts from the generated HTML report. Does your plugin provide a way to do that ?

**Comment by jaredsburrows** [comment]
@qkjerome No but I am open to PRs :)

**Comment by jaredsburrows** [comment]
Closing this for now. Ideally, you want to run `gradlew licenseReleaseReport` once before you publish your final APK.
