### ISSUE TITLE
Empty JSON Report

### ISSUE THREAD

**Issue by eygraber** [jaredsburrows/gradle-license-plugin#37]
I'm using v0.8.41, gradle v4.5.1, android plugin v3.0.1.

My applied plugins are:

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'
apply plugin: 'io.fabric'
apply plugin: 'com.jaredsburrows.license'
```

My `licenseReport` extension is:

```
licenseReport {
  generateHtmlReport = false
  generateJsonReport = true

  // These options are ignored for Java projects
  copyHtmlReportToAssets = false
  copyJsonReportToAssets = false
}
```

If I run `:app:license<my flavor>DebugReport` it completes and logs that it wrote the json report, but opening that file just shows `[]`.

My dependencies are a mix of local modules, and maven artifacts.

**Comment by jaredsburrows** [comment]
What does the HTML report say?

In this the correct way to use the extension @MatthewTamlin?

**Comment by eygraber** [comment]
@jaredsburrows The HTML report is also empty:

```
<html>
  <head>
    <style>body{font-family: sans-serif} pre{background-color: #eeeeee; padding: 1em; white-space: pre-wrap}</style>
    <title>Open source licenses</title>
  </head>
  <body>
    <h3>None</h3>
  </body>
</html>

```

**Comment by jaredsburrows** [comment]
What does the report say without using `licenseReport` extension?

**Comment by MatthewTamlin** [comment]
The config options are being used correctly. Unsure why no dependencies would be resolved.

**Comment by jaredsburrows** [comment]
@MatthewTamlin Thanks

@eygraber Can you share your build.gradle file?

**Comment by eygraber** [comment]
Removing the `licenseReport` extension didn't help.

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'
apply plugin: 'io.fabric'
apply plugin: 'com.jaredsburrows.license'

tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all { kotlinOptions { allWarningsAsErrors = true } }

repositories {
  jcenter()
  maven { url 'https://maven.fabric.io/public' }
}

android {
  compileSdkVersion project.compileSdkVersion
  defaultConfig {
    applicationId "com.myapp"
    minSdkVersion project.minSdkVersion // 21
    targetSdkVersion project.targetSdkVersion // 27
    versionCode 1
    versionName "1.0.0"
    testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    multiDexEnabled true
  }

  signingConfigs {
    debug {
      storeFile file('debug.keystore')
    }
  }

  buildTypes {
    release {
      minifyEnabled false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }

    debug {
      signingConfig signingConfigs.debug
      versionNameSuffix '-DEBUG'

      minifyEnabled false
      useProguard false
      proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
    }
  }

  flavorDimensions "environment"

  productFlavors {
    def version = ""

    sandbox {
      dimension "environment"

      applicationIdSuffix ".sandbox"
      // always use debug signing for dev builds, debug OR release
      signingConfig signingConfigs.debug
    }

    dev {
      dimension 'environment'

      applicationIdSuffix '.dev'
      // always use debug signing for dev builds, debug OR release
      signingConfig signingConfigs.debug
    }

    staging {
      dimension "environment"

      applicationId ".staging"
    }

    prod {
      dimension "environment"
    }
  }

  packagingOptions {
    pickFirst  'META-INF/*'
  }
}

androidExtensions {
  experimental = true
}

licenseReport {
  generateHtmlReport = false
  generateJsonReport = true

  // These options are ignored for Java projects
  copyHtmlReportToAssets = false
  copyJsonReportToAssets = false
}

dependencies {
  implementation project(':utils')
  implementation project(':kotlin')
  implementation project(':android')
  implementation project(':kodein')
  implementation project(':ui')
  implementation project(':logging')
  implementation project(':rx')
  implementation project(':realm')
  implementation project(':firebase')
  implementation project(':auth')
  implementation project(':models')
  implementation project(':notifications')

  // kotlin
  implementation deps.kotlin

  // android
  implementation "com.android.support:appcompat-v7:$supportLibVersion"
  implementation "com.android.support:design:$supportLibVersion"
  implementation "com.android.support:cardview-v7:$supportLibVersion"
  implementation deps.constraintLayout
  implementation deps.firebaseAuth
  implementation deps.firebase
  implementation deps.firebaseNotifications
  implementation "com.google.firebase:firebase-config:$googlePlayServicesVersion"
  implementation deps.location
  implementation "com.google.android.gms:play-services-maps:$googlePlayServicesVersion"

  implementation "com.google.maps.android:android-maps-utils:0.5"

  // utils
  implementation deps.rx
  implementation deps.rxAndroid
  implementation deps.rxKotlin
  implementation deps.rxCursorLoader

  implementation deps.rxBindingsPlatform
  implementation deps.rxBindingsRecyclerView
  implementation 'com.googlecode.libphonenumber:libphonenumber:8.8.9'

  implementation deps.kodein
  implementation deps.kodeinAndroid

  implementation 'com.github.salomonbrys.kotson:kotson:2.5.0'
  implementation("com.squareup.retrofit2:retrofit:$retrofitVersion") {
    exclude module: 'okhttp' // since we are importing our own to keep up to date
  }
  implementation "com.squareup.retrofit2:adapter-rxjava2:$retrofitVersion"
  implementation "com.squareup.retrofit2:converter-gson:$retrofitVersion"

  implementation deps.okHttp3

  implementation deps.timber
  implementation deps.timberKt

  implementation("com.mikepenz:fastadapter:3.1.2@aar") {
    transitive = false
  }
  implementation "com.mikepenz:fastadapter-commons:3.1.2@aar"
  implementation('com.crashlytics.sdk.android:crashlytics:2.8.0@aar') {
    transitive = true
  }
  implementation 'com.devbrackets.android:exomedia:4.1.0'

  implementation 'com.github.chrisbanes:PhotoView:2.1.3'

  implementation 'com.theartofdev.edmodo:android-image-cropper:2.6.0'

  implementation (deps.materialDialogs) { exclude group: 'com.android.support' }
  implementation (deps.materialDialogsCommons) { exclude group: 'com.android.support' }

  implementation 'com.flurgle:camerakit:0.9.18'

  implementation ("com.github.bumptech.glide:glide:$glideVersion") {
    exclude group: 'com.android.support'
  }
  implementation ("com.github.bumptech.glide:okhttp3-integration:$glideVersion") {
    exclude group: 'com.android.support'
  }

  implementation 'com.karumi:dexter:4.2.0'

  implementation ('com.wdullaer:materialdatetimepicker:3.4.0') {
    exclude group: 'com.android.support'
  }

  implementation 'com.airbnb.android:lottie:2.5.0'

  // debugging
  debugImplementation 'com.facebook.stetho:stetho:1.5.0'
  debugImplementation 'com.uphyca:stetho_realm:2.2.2'
  implementation "com.squareup.okhttp3:logging-interceptor:$okhttpVersion"

  // LeakCanary
  debugImplementation "com.squareup.leakcanary:leakcanary-android:$leakCanaryVersion"
  releaseImplementation "com.squareup.leakcanary:leakcanary-android-no-op:$leakCanaryVersion"
  testImplementation "com.squareup.leakcanary:leakcanary-android-no-op:$leakCanaryVersion"

  // unit tests
  testImplementation 'junit:junit:4.12'
  testImplementation('com.nhaarman:mockito-kotlin-kt1.1:1.5.0') {
    ['kotlin-stdlib', 'kotlin-reflect'].each { exclude module: it }
  }
  testImplementation 'org.mockito:mockito-core:2.15.0'
  testImplementation 'com.natpryce:hamkrest:1.4.2.2'

  androidTestImplementation "com.android.support:support-annotations:$supportLibVersion"

  androidTestImplementation 'com.android.support.test:runner:0.5'
  androidTestImplementation 'com.android.support.test.espresso:espresso-core:2.2.2'
}

apply plugin: 'com.google.gms.google-services'
```

**Comment by jaredsburrows** [comment]
Thanks. I will have to take a look into this. I have many tests around this. I am not sure what is going on.

**Comment by hardysim** [comment]
I have the same problem. The report-file is being created and copied to the asset-folder but empty (both, JSON and HTML).

I'm using `0.8.41` and tried running it manually for `licenseReleaseReport` and `licenseDebugReport` as well as using my automated run using the following script which used to work:

```gradle
project.afterEvaluate {
    preBuild.dependsOn project.tasks.getByName('licenseReleaseReport')
}
```

---

It stopped working once with no change to remember so maybe it's related to the Android Studio (3.1) or Gradle (4.6) versions?

**Comment by jaredsburrows** [comment]
@hardysim Using your above code used to work? My guess would be that I removed `project.evaluationDependsOnChildren()` here: https://github.com/jaredsburrows/gradle-license-plugin/commit/a3a60394fdac345343fdc83a792a9ff2788cfba9.

Does it work if you run it directly?

**Comment by hardysim** [comment]
> Does it work if you run it directly?

nope, it does not (I tried running it manually with `gradlew licenseDebugReport`)

**Comment by eygraber** [comment]
@jaredsburrows maybe the issue is related to multi-module projects? I just tried on my smallest module, and had the same issue with an empty report. It also created an HTML file even though I said not to (command was `./gradlew :utils:licenseReport`):

```
apply plugin: 'kotlin'
apply plugin: 'com.jaredsburrows.license'

licenseReport {
    generateHtmlReport = false
    generateJsonReport = true
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:1.2.31"
}
```

And the output was:

```
> Task :utils:licenseReport 
Wrote HTML report to /home/eygraber/workspace/myapp/utils/build/reports/licenses/licenseReport.html.
Wrote JSON report to /home/eygraber/workspace/myapp/utils/build/reports/licenses/licenseReport.json.

```

**Comment by hardysim** [comment]
Ah, I found the cause:
I'm using the [gradle-play-publisher](https://github.com/Triple-T/gradle-play-publisher) library as well and here the configuration changed with a recent version. Generating the licence-report **is working with the old-style configuration** of `gradle-play-publisher`.

So, I'm fine now (and created an [issue for this](https://github.com/Triple-T/gradle-play-publisher/issues/257)). Thank you guys.

**Comment by hardysim** [comment]
Oh hmm, it seems that it's not related to this lib. So **there is still a problem with empty reports**.

---

I had also disabled the kotlin-`experimental`-flag (needed for https://github.com/lisawray/groupie). I need to set this to make groupie working correctly but then the licence-reports are broken.

So, any idea why this flag breaks the reports?


PS: I see in the log, that when the reports are failing, there are no lines like `YXZ dependency does not have a license.` which use to show up when the reports are working.

**Comment by eygraber** [comment]
@jaredsburrows any update on this?

**Comment by jaredsburrows** [comment]
I will take a look tonight or this weekend. Most likely need to revert a
recent change. Does a previous version work?

Jared Burrows

*jaredsburrows@gmail.com <jaredsburrows@gmail.com>*
LinkedIn: https://www.linkedin.com/in/jaredsburrows

**Comment by eygraber** [comment]
I tried back until 0.6.0 (which didn't work at all), and the result was the same. `[]`

**Comment by jaredsburrows** [comment]
@eygraber All these versions? https://bintray.com/jaredsburrows/maven/gradle-license-plugin

I wonder if there is an edge case in your project? I have tests that use the latest AGP plugins and support multi module builds.

**Comment by eygraber** [comment]
@jaredsburrows removing:

```
androidExtensions {
  experimental = true
}
```

From my build.gradle fixed it. I look forward to hearing how that broke things :smile:

**Comment by eygraber** [comment]
That enables Kotlin experimental extensions for Android (view caching, parceling, etc...). Shouldn't be doing anything to the build environment really; I believe it's a flag for their annotation processor to process certain annotations, but I could be wrong.

**Comment by eygraber** [comment]
Sorry I was asking about getting this plugin to work when experimental extensions are enabled. Disabling it is not an option for me (and probably anyone using Kotlin with Android who is already using it).

**Comment by jaredsburrows** [comment]
For view caching(using the ID directly) you do not need to have `androidExtensions` block. Are you using anything else?

Also, if you only need this plugin for the generation, you can have an if/else check around `androidExtensions` to toggle it off so the plugin can work naturally.

I rather not add this code in this plugin because this plugin should work will all POM dependencies. I do not want to have to check for `androidExtensions` each time.

**Comment by eygraber** [comment]
We need it for the view caching for `LayoutContainer`, and we use `Parcelize`.

To be clear, you're suggesting to check if the license task is in the task graph, and if it is, disable androidExtensions? That should work for us (maybe add something to the readme here).

Does enabling androidExtensions pull in a dependency that the task can't handle? If so, I can file a bug on Kotlin for that.

**Comment by eygraber** [comment]
I tried (didn't want to duplicate for each project that uses it):

```
subprojects {
  project.plugins.whenPluginAdded { plugin ->
    if("org.jetbrains.kotlin.gradle.internal.AndroidExtensionsSubpluginIndicator" == plugin.class.name) {
      gradle.taskGraph.whenReady { taskGraph ->
        if(taskGraph.hasTask(":app:licenseDevDebugReport")) {
          project.androidExtensions.experimental = false
        }
      }
    }
  }
}
```

and that didn't fix it.

I'll be happy to file the bug, but they're more likely to take action if I can tell them why experimental being enabled breaks this plugin. Do you know what the cause is? I can look for it myself, but not knowing the codebase for this plugin all that well it could take some time.

**Comment by jaredsburrows** [comment]
I am not sure. I have not spent time to look at the Kotlin plugin source code. Here is a starting point: https://github.com/JetBrains/kotlin/blob/06903f803bb9ef9c2f8f625e428e8dcedf4cd3f9/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/internal/AndroidSubplugin.kt#L38.

**Comment by eygraber** [comment]
So all they do is dynamically add a dependency. Do you have an easy way to test your parser directly against a POM, so that I can see what the issue is?

**Comment by eygraber** [comment]
@jaredsburrows I did a little digging and it seems like the only difference between having `androidExtensions.experimental` on or off is that if it is enabled, then [`configuration.canBeResolved`](https://github.com/jaredsburrows/gradle-license-plugin/blob/ccbdb28b7d4551a54fee57f4834d04925d803c74/src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy#L110) returns `false` for every configuration except `compile`. That's why the result is `[]`; because all configurations with dependencies don't get processed due to `configuration.canBeResolved == false`.

I went a little further, and made a local copy of `LicenseReportTask` in my `build.gradle`. If `androidExtensions.experimental` is set to `false`, but I include the code (see snippet below) that is executed if it were set to `true` at the beginning of my local `LicenseReportTask`, then the licenses are properly generated, but my code that depends on experimental extensions fails to compile.

```
project.configurations.all { configuration ->
  if(configuration.name == "implementation") {
    configuration.dependencies.add(
      project.dependencies.create(
        "org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.2.41"
      )
    )
  }
}
```

**Comment by eygraber** [comment]
I also found a hack that works, although I reallllllly don't like it:

```
def isLicenseReportTaskRunning = gradle.startParameter.taskNames.any { taskName ->
  taskName ==~ "license.*Report"
}

if(isLicenseReportTaskRunning && gradle.startParameter.taskNames.size() > 1) {
  throw new IllegalArgumentException("licenseReport tasks must be the only task run per gradle invocation")
}

if(!isLicenseReportTaskRunning) {
  apply plugin: 'kotlin-android-extensions'

  androidExtensions {
    experimental = true
  }
}
```

**Comment by eygraber** [comment]
@jaredsburrows ever get a chance to look at this? I really don't like using the above workaround.

**Comment by jaredsburrows** [comment]
I am not sure really what you want me to do. I rather not support AGP + experimental Kotlin plugins.

**Comment by eygraber** [comment]
The plugin isn't experimental; the code in the artifact it downloads is. The issue seems to be related to when the configuration is resolvable, but I don't understand how that happens ([as I explain here](https://github.com/jaredsburrows/gradle-license-plugin/issues/37#issuecomment-387317480)).

In general, Kotlin experimental doesn't mean not production ready; [they mark it as such for compatibility when they make changes to the API](https://stackoverflow.com/questions/46240236/can-experimental-kotlin-coroutines-be-used-in-production).

**Comment by hannesstruss** [comment]
> I did a little digging and it seems like the only difference between having androidExtensions.experimental on or off is that if it is enabled, then configuration.canBeResolved returns false for every configuration except compile

It appears to me what is actually happening is that setting `configuration.canBeResolved = true` fails with `org.gradle.api.InvalidUserDataException: Cannot change role of configuration ':app:api' after it has been included in dependency resolution.`, for `api` and a few other configurations. 

When I move the assignment of `canBeResolved` out of the task execution phase and into the configuration phase, i.e. into `LicensePlugin.apply`, it seems to work. I'm not sure that has any other side effects, but couldn't find any material on this.

**Comment by eygraber** [comment]
@jaredsburrows Realm had a similar issue and fixed it here - https://github.com/realm/realm-java/pull/6088

**Comment by jaredsburrows** [comment]
Could you make a PR that include these changes and a test for it?

**Comment by pranavvij** [comment]
> @jaredsburrows Realm had a similar issue and fixed it here - [realm/realm-java#6088](https://github.com/realm/realm-java/pull/6088)

Could you please update us on this as my json is empty. I am trying to execute my task as show below.

```
afterEvaluate {
    assembleDebug.dependsOn licenseDebugReport
}
```

**Comment by jaredsburrows** [comment]
As of `0.8.90`, the JSON report works, but it looks like it not being copied to the correct location.

```
$ gradlew licenseDebugReport 
> Task :app:licenseDebugReport
Wrote CSV report to file:///Users/noname/repo/android-gif-example/app/build/reports/licenses/licenseDebugReport.csv.
Copied CSV report to file:///Users/noname/repo/android-gif-example/app/src/main/assets/open_source_licenses.csv.
Wrote HTML report to file:///Users/noname/repo/android-gif-example/app/build/reports/licenses/licenseDebugReport.html.
Copied HTML report to file:///Users/noname/repo/android-gif-example/app/src/main/assets/open_source_licenses.html.
Wrote JSON report to file:///Users/noname/repo/android-gif-example/app/build/reports/licenses/licenseDebugReport.json.

BUILD SUCCESSFUL in 3s
```

I want to update the "defaults" but this does work:
```
licenseReport {
  generateJsonReport = true
  copyJsonReportToAssets = true
}
```

**Comment by jaredsburrows** [comment]
@pranavvij 

This works:

```
tasks.whenTaskAdded {
  if (name == "assembleDebug") {
    dependsOn("licenseDebugReport")
  }
}

tasks.whenTaskAdded {
  if (name == "assembleRelease") {
    dependsOn("licenseReleaseReport")
  }
}
```
