### ISSUE TITLE
Resolving artifacts may take exponential execution time

### ISSUE THREAD

**Issue by monae** [jaredsburrows/gradle-license-plugin#394]
In current (0.9.3) implementation, `getResolvedArtifactsFromResolvedDependencies` doesn't check whether it is already called for each `resolvedDependency`.
As a result, for projects with complex dependencies, this process may be called multiple times for the same dependency object, and in the worst case the number of times increases exponentially.
This causes the command to take a very long time to run, almost resulting in a hang.

This problem can be fixed by recording the dependencies that have already been processed.
Here is my sample implementation.
https://github.com/monae/gradle-license-plugin/commit/82c683240937225a2d5f8fd729df73bfebfcaea8

**Comment by monae** [comment]
I wrote a test for this situation. This test takes about 2 minutes on my machine before the patch is applied, but now takes only a few seconds after the patch is applied. Increasing the `depth` parameter will cause the execution time to increase more exponentially before patching, but will only increase linearly after patching.
https://github.com/monae/gradle-license-plugin/commit/3fe4e5d429dbc9c00dd4919a733efa06d4707f85

If it's OK, I will make a PR.

**Comment by shashachu** [comment]
yep we're running into the same issue and I locally made a very similar change to make it work. Went from > 20 mins (I eventually canceled it) to ~30s.

**Comment by jaredsburrows** [comment]
@monae Thanks. Yes, send the PR, PRs are always welcome.
