### ISSUE TITLE
Need to enhance known licenses list

### ISSUE THREAD

**Issue by monae** [jaredsburrows/gradle-license-plugin#395]
On HTML report, some libraries are not correctly listed because they define their licenses with slightly different names.
I want to resolve this issue by enhancing "the known licenses list" in `LicenseHelper` class.
A sample implementation is here. Ambiguous names and unofficial URLs are excluded.
https://github.com/monae/gradle-license-plugin/commit/a6dd5ce9f4ad88c0d6d353876e49c529bbd6969a

---

List of libraries I found:

https://mvnrepository.com/artifact/com.airbnb.android/epoxy/5.1.3
```xml
<name>Apache-2.0</name>
<url>https://github.com/airbnb/epoxy/blob/master/LICENSE</url>
```

https://mvnrepository.com/artifact/com.facebook.android/audience-network-sdk/6.16.0
```xml
<name>Apache License Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0</url>
```

https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib/1.9.22
```xml
<name>The Apache License, Version 2.0</name>
<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
```

https://mvnrepository.com/artifact/com.facebook.shimmer/shimmer/0.5.0
```xml
<name>BSD 2-Clause License</name>
<url>https://github.com/facebook/shimmer-android/blob/master/LICENSE</url>
```

https://mvnrepository.com/artifact/com.samskivert/jmustache/1.16
```xml
<name>The (New) BSD License</name>
<url>http://www.opensource.org/licenses/bsd-license.php</url>
```

https://mvnrepository.com/artifact/org.ow2.asm/asm/9.6
```xml
<name>BSD-3-Clause</name>
<url>https://asm.ow2.io/license.html</url>
```

https://mvnrepository.com/artifact/org.jsoup/jsoup/1.17.2
```xml
<name>The MIT License</name>
<url>https://jsoup.org/license</url>
```

**Comment by jaredsburrows** [comment]
Feel free to send a PR to update the existing list.

**Comment by jaredsburrows** [comment]
Closed by https://github.com/jaredsburrows/gradle-license-plugin/pull/402
