### ISSUE TITLE
Ignore Gradle Subprojects and Unspecified versions

### ISSUE THREAD

**Issue by jaredsburrows** [jaredsburrows/gradle-license-plugin#4]
## Exception:
```
$ ./gradlew licenseDebugReport
:blah:licenseDebugReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':blah:licenseDebugReport'.
> Could not resolve all dependencies for configuration ':blah:poms'.
   > Could not find blah:unspecified.
     Searched in the following locations:
         https://plugins.gradle.org/blah-unspecified.pom
         file:/Users/<>/blah-unspecified.pom
         http://dl.bintray.com/blah-unspecified.pom
         https://repo1.maven.org/blah-unspecified.pom
         https://jcenter.bintray.com/blah-unspecified.pom
     Required by:
         project :blah
```

**Comment by benjamin-bader** [comment]
I came here to say the same thing!

Is the intent of this issue to entirely disregard submodules, or will this also report on their own dependencies?

**Comment by jaredsburrows** [comment]
@benjamin-bader That's a good question. I believe I should either skip or traverse into the `subproject`.

**Comment by benjamin-bader** [comment]
Without knowing anything about how feasible it is, I'd vote for traversing - skipping sounds like the report might end up missing important dependencies.

**Comment by jaredsburrows** [comment]
@benjamin-bader I agree. I am working on adding tests and support for this now.

**Comment by tmtrademarked** [comment]
Any updates on this? It would be very handy to be able to use this for my project, which contains modules. :-)

**Comment by jaredsburrows** [comment]
@tmtrademarked I am working on it! I need to most likely iterate through artifacts instead of configurations. Sorry for the wait.

**Comment by tmtrademarked** [comment]
No worries! Thanks for the response and the excellent plugin. :-)

**Comment by jaredsburrows** [comment]
@tmtrademarked It should be fixed soon. Have you tested how the reports look when you "commented" out your modules? Let me know of suggestions/improvements as well.

**Comment by cezium** [comment]
Any progress on this issue? It's currently a show stopper

**Comment by jaredsburrows** [comment]
@cezium Sorry about the way. I will try to work on it this weekend!

**Comment by jaredsburrows** [comment]
This commit: https://github.com/jaredsburrows/gradle-license-plugin/commit/f2725455452c350561eb45b42954748a09cf9fb6 should have solved this issue. I making a `0.6.0` release now.

**Comment by benjamin-bader** [comment]
Works great for us - thanks!

**Comment by jaredsburrows** [comment]
@benjamin-bader Awesome! Thanks for your feedback. I am going to close this for now.

@tmtrademarked @cezium Please let me know if you are still having any issues.

**Comment by martinbonnin** [comment]
Looks like it's still not working for me. You can reproduce with this repo https://github.com/martinbonnin/TestLicenses

It has a `library` module which declares a dependency on `ormlite` but can't find any `ormlite` mention in the generated files

**Comment by jaredsburrows** [comment]
@martinbonnin What is the error you are seeing?
I am seeing:
```
$ gradlew licenseDebugReport

> Configure project :app
Configuration 'compile' in project ':app' is deprecated. Use 'implementation' instead.

> Task :app:licenseDebugReport
Wrote HTML report to /Users/noname/repo/TestLicenses/app/build/reports/licenses/licenseDebugReport.html.
Wrote JSON report to /Users/noname/repo/TestLicenses/app/build/reports/licenses/licenseDebugReport.json.


BUILD SUCCESSFUL in 2s
1 actionable task: 1 executed
```
Here is the image:
<img width="679" alt="screen shot 2018-03-14 at 4 27 25 pm" src="https://user-images.githubusercontent.com/1739848/37436325-a10fa0da-27a4-11e8-834e-4de514438960.png">

**Comment by benjamin-bader** [comment]
It looks like the bug is that there is no license entry for `ormlite`.

**Comment by jaredsburrows** [comment]
@benjamin-bader O! I can create a possible "default" or try to show what exists in the current POM file. I'll explore the POM file of `ormlite`.

**Comment by jaredsburrows** [comment]
@benjamin-bader @martinbonnin After spending sometime writing tests around this. My project currently handles:
 - multiple java modules
 - android and java modules
 - but not an android app module and a android library module

**Comment by martinbonnin** [comment]
Yeah, this has to do with multi variant somehow. The plugin cannot resolve the android library dependencies due to errors like:

`Execution failed for task ':app:licenseReleaseReport'.
> Could not resolve all dependencies for configuration ':app:implementation'.
> Could not resolve project :library.
 Required by:
     project :app
  > Cannot choose between the following configurations of project :library:
      - debugApiElements
      - debugRuntimeElements
      - releaseApiElements
      - releaseRuntimeElements`
