### ISSUE TITLE
Possibility for different HTML report file name for each module

### ISSUE THREAD

**Issue by ghost** [jaredsburrows/gradle-license-plugin#40]
Following situation: 

There is an app which consist of two modules:  app itself and SDK it's being built upon.
If I apply this plugin to both modules, it will 2 create assets/open_source_licenses.html files -one per module. So when I build the APK, one of the files is naturally lost. 

Solution that would work in my case is to have for example automatic naming per module: like assets/open_source_licenses_sdk.html 

Thanks.

**Comment by jaredsburrows** [comment]
Have you tried just applying this to the "app" module? You only need the license file for the end production app.

**Comment by appmagnetics** [comment]
Yes, this will only include modules used by the app, not by sdk.

**Comment by jaredsburrows** [comment]
@appmagnetics Are you saying it does not go into your `implementation project(':mylib')` dependencies? I have tests for that particular situation.

**Comment by appmagnetics** [comment]
@jaredsburrows 
we are not using Gradle 3.x so these are the including lines: 

debugCompile project(path: ':sdk', configuration: 'debug')
releaseCompile ‘co.my.sdk:mysdk-android-3.7.0@aar'

**Comment by jaredsburrows** [comment]
@appmagnetics That is fine. I am wondering if the plugin is not picking up project(path: ':sdk', configuration: 'debug')?

**Comment by jaredsburrows** [comment]
For this to work properly, you should be using `releaseCompile project(path: ':sdk', configuration: 'release')`. I believe it gets stuck on the AAR.

**Comment by jaredsburrows** [comment]
Are you still seeing this?

**Comment by appmagnetics** [comment]
Sorry I cannot verify it any more since I no longer working in that company and have no access to the source code.

**Comment by jaredsburrows** [comment]
Closing this for now since this plugin is meant for a HTML report for 1 app.
