### ISSUE TITLE
Project group order on HTML report is unstable

### ISSUE THREAD

**Issue by monae** [jaredsburrows/gradle-license-plugin#409]
In HTML reports, the order of projects within the same group is sorted by name, but the order of the groups themselves is not stable.
This can result in large diffs in the output report even with small changes in project dependencies.

This issue can be fixed by sorting these groups in a certain order.
However, this may be a breaking change, and the choice of the order is questionable, so I think some discussion is needed.
Sample implementation: https://github.com/monae/gradle-license-plugin/commit/93b28f5a1d2d1c0df62b947432bd4bfe5b26d8a2

**Comment by jaredsburrows** [comment]
Ok, please send a PR!
