### ISSUE TITLE
Firebase license is not included in report

### ISSUE THREAD

**Issue by appmagnetics** [jaredsburrows/gradle-license-plugin#42]
Following dependencies are used: 

    compile 'com.android.support:support-v4:25.3.1'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    compile 'com.squareup.okhttp3:okhttp:3.8.1'
    compile 'com.google.firebase:firebase-messaging:10.0.1'
    compile 'com.googlecode.libphonenumber:libphonenumber:8.4.2'

But firebase does not manage to be included in the report: 

<img width="538" alt="screen shot 2018-04-16 at 12 15 08" src="https://user-images.githubusercontent.com/7034162/38803620-13174d9c-4170-11e8-858c-2f12cf8b69bb.png">

Is there is may be something specific at the fact how firebase license file is published?
Could you shortly explain how the plugin works, where it takes the license info?

**Comment by jaredsburrows** [comment]
Firebase is closed source.
