### ISSUE TITLE
Dependencies without poms are ignored

### ISSUE THREAD

**Issue by markhoughton** [jaredsburrows/gradle-license-plugin#43]
If a dependency exists but doesn't have a pom associated with it, this plugin will not include the dependency in either the HTML or JSON reports, or in the console logging.

We get logging when a dependency doesn't have any license info listed in the pom, but nothing is logged when the pom itself is not found.

**Comment by jaredsburrows** [comment]
Can you show an example of a dependency without a POM?

**Comment by jaredsburrows** [comment]
Since we print out dependencies without licenses in #17, I am closing this. See this logging: https://github.com/jaredsburrows/gradle-license-plugin/commit/08dc12e048c131c67adb06882b8a63dece4dc930#diff-d80ecee9904217d739f465cdc0085e2aR128.
