### ISSUE TITLE
Publish to Maven Central?

### ISSUE THREAD

**Issue by hidroh** [jaredsburrows/gradle-license-plugin#47]
Hi, this is not a request but rather I would like to know your thought about publishing this plugin to Maven Central as well?

Jcenter has some recent changes that break builds and there have been some public debates about switching from `jcenter()` to `mavenCentral()` (or `google()` when appropriate), which I'd rather not quote here.

I think it would be nice if there is an option to adopt this plugin via Maven Central as well, if that's possible at all.

**Comment by jaredsburrows** [comment]
What changes are breaking builds? This plugin is published on both `jcenter()` and `gradlePluginPortal()`. I believe `gradlePluginPortal()` mirrors both `jcenter()` and `mavenCentral()`.

**Comment by hidroh** [comment]
It's not this plugin breaking builds. Long story short on jcenter it's because `jcenter()` mirrors `google()` dependencies unnecessarily. Re `gradlePluginPortal()`, does it ultimately rely on `jcenter()`, or itself is a repository?
