### ISSUE TITLE
Version is null for some dependencies

### ISSUE THREAD

**Issue by amnong** [jaredsburrows/gradle-license-plugin#48]
For example, in my project, we use Apache HttpCore, and the JSON file contains this entry:
```
{
    "project": "Apache HttpCore",
    "description": "Apache HttpComponents Core (blocking I/O)",
    "version": null,
    "developers": [

    ],
    "url": "http://hc.apache.org/httpcomponents-core-ga",
    "year": "2005",
    "licenses": [
        {
            "license": "Apache License, Version 2.0",
            "license_url": "http://www.apache.org/licenses/LICENSE-2.0.txt"
        }
    ]
},
```

Version should be extractible from some location. For example, plugin "Gradle-License-Report" managed to figure out that in my project we use httpcore 4.4.9 (they titled it "Manifest version"). That plugin does not feature a JSON report mode, which is why I wanted to use your plugin, but sadly the JSON report doesn't specify the version for many of our dependencies.

Your efforts will be highly appreciated, keep up the good work, and thanks for the plugin :)

**Comment by jaredsburrows** [comment]
I found the POM here: http://central.maven.org/maven2/org/apache/httpcomponents/httpcore/4.4.9/httpcore-4.4.9.pom. The POM does include the version. I will take a look.

**Comment by amnong** [comment]
Hi @jaredsburrows, thanks again for this lovely project. I was wondering if you had a chance to examine the problem.

Thanks!
Amnon

**Comment by jaredsburrows** [comment]
I am updating this project and converting it to Kotlin. I have also updated the tests to use the newer Gradle test suite. Once I am done, it should be much easier to setup a test to fix this.

**Comment by amnong** [comment]
Cool, thanks for the update! I admit in the meantime I had to find an alternative, so I'm using another plugin for now.
