### ISSUE TITLE
No year and no developer shown in HTML

### ISSUE THREAD

**Issue by JohannesPtaszyk** [jaredsburrows/gradle-license-plugin#50]
It would be nice to have the year and developer shown for each entry in the HTML file.

Also the License in the HTML looks a little bit off, since the String "Copyright [yyyy] [name of copyright owner]" is not really appealing.

I myself got no experience in groovy, so it would be nice if you could have a look at the issue.

**Comment by jaredsburrows** [comment]
This is currently in the JSON format and not the HTML format. So you just want the same details in the HTML as well?

**Comment by jaredsburrows** [comment]
I'd gladly accept a PR as well :)

**Comment by jaredsburrows** [comment]
No PR?
