### ISSUE TITLE
Generate Report fails with below Error

### ISSUE THREAD

**Issue by dsampangi** [jaredsburrows/gradle-license-plugin#51]
:emp-api:licenseReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':emp-api:licenseReport'.
> **Could not find property 'canBeResolved' on configuration ':emp-api:compile'.**

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by jaredsburrows** [comment]
What type of project is `emp-api`? This should have been bypassed by https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy#L71.

**Comment by jaredsburrows** [comment]
What version of the plugin are you using?

**Comment by jaredsburrows** [comment]
Docs on `canBeResolved `: https://docs.gradle.org/current/userguide/declaring_dependencies.html#sec:resolvable-consumable-configs.

Closing this since it sounds like you are using an older Gradle version.
