### ISSUE TITLE
Identical license shows up twice

### ISSUE THREAD

**Issue by piegamesde** [jaredsburrows/gradle-license-plugin#52]
I just generated a report and noticed that the Apache License 2.0 shows up in there twice. The first time for:
- Apache Log4j API
- Apache Log4j Commons Logging Bridge
- Apache Log4j Core
and the second time for:
- Apache Commons Logging
- Elsa Serialization
- Gson
- Guava: Google Core Libraries for Java
- Kotlin-runtime
- Kotlin-stdlib
- LZ4 and xxHash
- Mapdb
- Picocli - a mighty tiny Command Line Interface

The license text section in both is identical. So I had a look at the json, Mapdb here:

    {
        "project": "Mapdb",
        "description": "MapDB provides concurrent Maps, Sets and Queues backed by disk storage or off-heap memory. It is a fast, scalable and easy to use embedded Java database.",
        "version": "3.0.5",
        "developers": [
            "Jan Kotek"
        ],
        "url": "http://www.mapdb.org",
        "year": null,
        "licenses": [
            {
                "license": "The Apache Software License, Version 2.0",
                "license_url": "http://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        ]
    },

And now log4j:

    {
        "project": "Apache Log4j API",
        "description": "The Apache Log4j API",
        "version": null,
        "developers": [
            
        ],
        "url": null,
        "year": null,
        "licenses": [
            {
                "license": "Apache License, Version 2.0",
                "license_url": "https://www.apache.org/licenses/LICENSE-2.0.txt"
            }
        ]
    },

Both license URLs are exactly the same, except for the http**s**.

**Comment by jaredsburrows** [comment]
Fixed here: https://github.com/jaredsburrows/gradle-license-plugin/pull/57.
