### ISSUE TITLE
Running multiple build variant license tasks crashes build

### ISSUE THREAD

**Issue by egargan** [jaredsburrows/gradle-license-plugin#55]
In a project with a few different build variants, running a full `gradle build` results in a crash.

The crash seems to be caused by each variant's license task conflicting with one another. When the first license task runs, [it creates a configuration called 'poms'](https://github.com/jaredsburrows/gradle-license-plugin/blob/master/src/main/groovy/com/jaredsburrows/license/LicenseReportTask.groovy#L67). Then when the second variant's license task runs, it attempts to create the same configuration, which crashes since it already exists.

Here's a small example app that demos this issue: https://github.com/egargan/license-plugin-issue-demo.

The error output can be viewed in the  [/gradle-build-error-output](https://github.com/egargan/license-plugin-issue-demo/blob/master/gradle-build-error-output) file. The [/app/build.gradle](https://github.com/egargan/license-plugin-issue-demo/blob/master/app/build.gradle) file sets up the calls to each task.

**Comment by jaredsburrows** [comment]
I get this error:
```
$ gradlew build

> Task :app:licenseDebugReport 
Wrote HTML report to file:///Users/noname/repo/license-plugin-issue-demo/app/build/reports/licenses/licenseDebugReport.html.
Wrote JSON report to file:///Users/noname/repo/license-plugin-issue-demo/app/build/reports/licenses/licenseDebugReport.json.


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:licenseReleaseReport'.
> Cannot add a configuration with name 'poms' as a configuration with that name already exists.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 12s
30 actionable tasks: 30 executed
```

**Comment by egargan** [comment]
Yep that's the issue we're getting too, is this expected behaviour? We're currently just deleting the 'poms' configuration after each task which seems to work fine - we get good output from the license task for each build variant. I'm thinking maybe this is something that should be done by the task itself?

**Comment by jaredsburrows** [comment]
Maybe we should create a separate configuration per variant?

**Comment by egargan** [comment]
Thanks for addressing this!
