### ISSUE TITLE
Task 'licenseReport' not found in root project (multiple projects)

### ISSUE THREAD

**Issue by 030** [jaredsburrows/gradle-license-plugin#63]
I have added the following to the build.gradle file of one of the projects:

```
plugins {
    id "com.jaredsburrows.license" version "0.8.42"
}
```

but the licenseReport task cannot be found, but while it is available when I added the plugin to a project that I downloaded from the springInitializer then it works.

Could you indicate whether this plugin should also work in a multi project?

**Comment by jaredsburrows** [comment]
What does your project structure look like? Can you post the error here?

**Comment by jaredsburrows** [comment]
Bump

**Comment by 030** [comment]
This works:

projectA/build.gradle

This does not work:

projects/some-projects/projectA/build.gradle
projects/some-projects/projectB/build.gradle
projects/some-projects/projectC/build.gradle
projects/some-projects/projectD/build.gradle
projects/some-projects/projectE/build.gradle

**Comment by jaredsburrows** [comment]
Where is the plugin being applied at? `projects/build.gradle` or in each `projects/some-projects/projectX/build.gradle`?

**Comment by 030** [comment]
First I enabled it in `projects/build.gradle`, then per project. None of them works. I ran both gradle build in debug mode, but I could not find a cause.

**Comment by jaredsburrows** [comment]
What do these `build.gradle` files look like? Do they use `java` or `android` plugins?

**Comment by 030** [comment]
It is only java code and their are only java plugins. For example, the gradle ben manes plugin is included as a plugin as well and works in this structure.

**Comment by jaredsburrows** [comment]
Maybe I will take a look at the following: https://github.com/ben-manes/gradle-versions-plugin/blob/master/src/main/groovy/com/github/benmanes/gradle/versions/VersionsPlugin.groovy#L28.

**Comment by eighthave** [comment]
I'm currently doing a mass survey of the licenses used in Android apps, so it would be very useful to be able to run `./gradlew licenseReport` on all the apps.  But I have  the same issue as the original reporter.  Here is an free software project as an example:
https://github.com/ProtonVPN/android-app

```console
 ~/.../protonvpn/android-app $ ./gradlew licenseReport
Starting a Gradle Daemon, 1 incompatible Daemon could not be reused, use --status for details

> Configure project :app
WARNING: DSL element 'DexOptions.incremental' is obsolete and will be removed soon.
Directory for versionName: /home/hans/code/protonvpn/android-app
Directory for versionCode: /home/hans/code/protonvpn/android-app
Directory for versionName: /home/hans/code/protonvpn/android-app
Directory for versionName: /home/hans/code/protonvpn/android-app
Directory for versionCode: /home/hans/code/protonvpn/android-app
Directory for versionName: /home/hans/code/protonvpn/android-app

> Configure project :openvpn
[assemble, assembleAndroidTest, build, buildDependents, buildEnvironment, buildNeeded, check, clean, cleanBuildCache, compileLint, components, connectedCheck, consumeConfigAttr, dependencies, dependencyInsight, dependentComponents, deviceCheck, extractProguardFiles, generateOpenVPN3Swig, help, kotlinDslAccessorsReport, lint, lintFix, model, preBuild, prepareKotlinBuildScriptModel, projects, properties, resolveConfigAttr, sourceSets, tasks, uninstallAll]

FAILURE: Build failed with an exception.

* What went wrong:
Task 'licenseReport' not found in root project 'android-app'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 6.0.
Use '--warning-mode all' to show the individual deprecation warnings.
See https://docs.gradle.org/5.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 7s
 ~/.../protonvpn/android-app $ ./gradlew tasks|grep -i license
licenseBlueDebugReport - Outputs licenses report for BlueDebug variant.
licenseBlueReleaseReport - Outputs licenses report for BlueRelease variant.
licenseDevDebugReport - Outputs licenses report for DevDebug variant.
licenseDevReleaseReport - Outputs licenses report for DevRelease variant.
licenseProdDebugReport - Outputs licenses report for ProdDebug variant.
licenseProdReleaseReport - Outputs licenses report for ProdRelease variant.
```

**Comment by jaredsburrows** [comment]
I believe this is resolved, I am using this in the root project here - https://github.com/jaredsburrows/android-gif-example/blob/master/build.gradle.kts#L20.
