### ISSUE TITLE
More dependency details 

### ISSUE THREAD

**Issue by natnan** [jaredsburrows/gradle-license-plugin#70]
Hi. Thanks for the plugin, it's been quite useful.

I got this strange requirement of reporting a very detailed licensing information each dependency including the transitive ones. That adds up to about ~180 dependencies, which means it's better be automated.

I managed to compile something using your library and a python script using the output json but there is still a lot to do. I noticed there are quite a lot more useful fields in pom files. I thought I could just get them but maven inheritance seems a little complex to deal with and you seem to have already implemented the traversing logic.

On a quick look these could be useful though some of them are maybe too much detail. Just gonna give examples from jersey project's POM instead of explaining

- name: `<name>jersey</name>` Children of the project will have more specific names of course.
- url: `<url>https://jersey.java.net/</url>`
- organization: `<organization><name>Oracle Corporation</name><url>http://www.oracle.com/</url></organization>`
- mailingLists: `<mailingLists><mailingList><name>Announcements</name><archive>http://java.net/projects/jersey/lists/announce/archive</archive><post>announce@jersey.java.net</post></mailingList>.....`
- scm: `<scm><connection>scm:git:git://java.net/jersey~code</connection><developerConnection>scm:git:ssh://git.java.net/jersey~code</developerConnection><url>http://java.net/projects/jersey/sources/code/show</url><tag>2.25.1</tag></scm>`
- issueManagement: `<issueManagement><system>JIRA</system><url>http://java.net/jira/browse/JERSEY/</url></issueManagement>`
- ciManagement: `<ciManagement><system>Hudson</system><url>http://hudson.glassfish.org/job/Jersey-trunk-multiplatform/</url></ciManagement>`
- developers: `<developers><developer><name>Pavel Bucek</name><organization>Oracle Corporation</organization><organizationUrl>http://www.oracle.com/</organizationUrl><url>https://blogs.oracle.com/PavelBucek</url></developer>.....`

Also specific to my use case but maybe.. A list of dependencies that depends on this dependency. Could be built while traversing. It is already provided by `dependencies` task of gradle but not really in a scripting friendly way.

I could try to take a shot at this and make a PR but my 0 experience with Groovy made it quite difficult to read the code when I was trying to figure out where you were getting the licensing information. So the result might be a little ugly :).

**Comment by jaredsburrows** [comment]
What information do you think would be useful for open source license information?

**Comment by natnan** [comment]
name, url, organization and developers are I think would be good to have.

**Comment by jaredsburrows** [comment]
Name, url and developers are already in HTML and JSON reports.

**Comment by natnan** [comment]
OK, thanks. Let's close this then.

I created this issue a while ago. I don't even remember what exactly I was trying to fix but now I realize I may have come to the wrong repository at the time :). Considering my script uses https://github.com/hierynomus/license-gradle-plugin/. Sorry about that.

But cool to know those things are in already and the plugin is being maintained. I might migrate to this.

**Comment by jaredsburrows** [comment]
@natnan If you start using my plugin and want more details, feel free to reopen this or submit a PR!
