### ISSUE TITLE
Add option to define asset folder and file name

### ISSUE THREAD

**Issue by AlexanderEggers** [jaredsburrows/gradle-license-plugin#79]
It would be quite useful if the plugin allows devs to define the asset folder destination and the related file name (both for the json and html).

**Comment by jaredsburrows** [comment]
Do you mean a folder within the "asset" folder?

**Comment by AlexanderEggers** [comment]
As much as I remember the plugin generates a folder which is located in a fixed location. It would be great if you could define that location yourself including the actual file name of the output.
